config/routes.rb
Rails.application.routes.draw do
  root to: "blogs#index"

  resources :admin, only: [:index, :create] do
    collection do
      get :logout
      get :blogs
    end
  end

  resources :blogs do
    collection do
      get "archive"
      get :single_view
    end
  end
end

app/models/admin_user.rb
class AdminUser
  include ActiveModel::Model
  attr_accessor :username, :password

  def login_valid?
    username == ENV["ADMIN_USERNAME"] && password == ENV["ADMIN_PASSWORD"]
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_attached_file :eye_catch, :styles => { :small => "150x150>" },
    :url  => "/assets/blog_images/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/blog_images/:id/:style/:basename.:extension"

  validates_attachment_content_type :eye_catch, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_presence :eye_catch
  validates :title, :contents, presence: true

  scope :recent, -> {
    order("created_at DESC")
  }
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authentication_required!, only: ["blogs"]

  def index
    if session[:current_user]
      redirect_to blogs_admin_index_path
    else
      @admin_user = AdminUser.new
    end
  end

  def create
    admin_user_params = params.require(:admin_user)
    @admin_user = AdminUser.new
    .tap { |su| su.username = admin_user_params[:username] }
    .tap { |su| su.password = admin_user_params[:password] }
    if @admin_user.login_valid?
      session[:current_user] = true
      redirect_to blogs_admin_index_path
    else
      @admin_user.password = nil
      flash[:notice] = 'Sorry, wrong credentils'
      render "index"
    end
  end

  def blogs
    @blogs = Blog.all.recent
  end

  def logout
    reset_session
    redirect_to  admin_index_path
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    if session[:current_user]
      redirect_to "/admin_blogs"
    else
      @admin_user = AdminUser.new
    end
  end

  def create
    admin_user_params = params.require(:admin_user)
    @admin_user = AdminUser.new
    .tap { |su| su.username = admin_user_params[:username] }
    .tap { |su| su.password = admin_user_params[:password] }
    if @admin_user.login_valid?
      session[:current_user] = true
      redirect_to "/admin_blogs"
    else
      @admin_user.password = nil
      flash[:notice] = 'Sorry, wrong credentils'
      render "index"
    end
  end

  def logout
    reset_session
    redirect_to  "/admins"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  ApplicationNotAuthenticated = Class.new(StandardError)

  rescue_from ApplicationNotAuthenticated do
    respond_to do |format|
      format.json { render json: { errors: [message: "401 Not Authorized"] }, status: 401 }
      format.html do
        flash[:notice] = "Not Authorized to access this page, plese log in"
        redirect_to "/admin"
      end
      format.any { head 401 }
    end
  end

  def authentication_required!
    session[:current_user] || raise(ApplicationNotAuthenticated)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :authentication_required!, only: ["new", "edit"]
  BLOG_PER_PAGE = 5

  def index
    @blogs = Blog.all.recent.first(BLOG_PER_PAGE)
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blogs_admin_index_path, notice: "Successfully Created"
    else
      render :new
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update_attributes(blog_params)
      redirect_to blogs_admin_index_path, notice: "Successfully Updated"
    else
      render :edit
    end
  end

  def archive
    @blogs = Blog.all.recent.page(params[:page]).per(BLOG_PER_PAGE)
    @total_page = @blogs.total_count / BLOG_PER_PAGE
    @total_page = @total_page.zero? ? 1 : @total_page
  end

  def single_view
    @blog = Blog.find(params[:blog_id])
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :contents, :eye_catch)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/blogs.html.erb
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <meta name="description" content="sample text,sample tex">
  <meta name="keywords" content="word1,word2,word3">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta property="og:title" content="">
  <meta property="og:description" content="sample text,sample tex">
  <meta property="og:url" content="">
  <meta property="og:site_name" content="">
  <meta property="og:type" content="blog">
  <meta property="fb:admins" content="">
  <meta property="og:image" content="assets/images/common/ogp.png">
  <meta name="apple-mobile-web-app-title" content="">
  <link rel="shortcut icon" href="assets/images/common/favicon.ico">
  <link rel="apple-touch-icon-precomposed" href="images/common/apple-touch-icon-precomposed.png">
</head>

<body id="js-body">
  <div id="fb-root"></div>

  <noscript class="for-no-js">Javascriptを有効にしてください。</noscript>
  <div class="for-old">お使いのOS・ブラウザでは、本サイトを適切に閲覧できない可能性があります。最新のブラウザをご利用ください。</div>

  <input type="hidden" value="./" id="js-base-url">

  <div class="l-wrap js-wrap">
    <div class="l-header l-header-admin js-header">
      <div class="l-header-top u-clear">
        <div class="l-header-logo">
          <%= link_to root_path, class: "logo" do %>
            <%= image_tag("logo-admin.png", height: "28", width: "138") %>
          <% end %>
        </div>
        <div class="l-header-text">
          <%= link_to "LOGOUT", logout_admin_index_path %>
        </div>
      </div>
    </div>

    <div class="l-container u-clear">
      <div class="l-main js-main">
      <div class="l-main-block"></div>
      <%= link_to "New Article", new_blog_path, class: "button button-text l-main-button" %>
      <ul class="archive archive-admin">
        <% if flash[:notice].present? %>
          <div style="color: green;" id="flash"><%= flash[:notice]  %></div>
        <% end %>
        <% @blogs.each do |blog| %>
          <li class="archive-item">
            <%= link_to edit_blog_path(blog), class: "post-article" do %>
              <div class="post-article-date" datetime="2016-9-16"><%= blog.created_at.strftime("%F") %></div>
              <h1 class="post-article-title"><%= blog.title %></h1>
            <% end %>
          </li>
        <% end %>
      </ul>
      </div>
    </div>

    <div class="l-footer l-footer-admin">
      <div class="l-footer-copyright">
        <small class="copyright">&copy;copyright</small>
      </div>
    </div>
  </div>
</body>

<% content_for :extra_javascripts do %>
  <%= javascript_include_tag "admin" %>
<% end %>

app/views/admin/index.html.erb
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <meta name="description" content="sample text,sample tex">
  <meta name="keywords" content="word1,word2,word3">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta property="og:title" content="">
  <meta property="og:description" content="sample text,sample tex">
  <meta property="og:url" content="">
  <meta property="og:site_name" content="">
  <meta property="og:type" content="blog">
  <meta property="fb:admins" content="">
  <meta property="og:image" content="assets/images/common/ogp.png">
  <meta name="apple-mobile-web-app-title" content="">
  <link rel="shortcut icon" href="assets/images/common/favicon.ico">
  <link rel="apple-touch-icon-precomposed" href="images/common/apple-touch-icon-precomposed.png">
</head>

<body id="js-body">
  <div id="fb-root"></div>

  <noscript class="for-no-js">Javascriptを有効にしてください。</noscript>
  <div class="for-old">お使いのOS・ブラウザでは、本サイトを適切に閲覧できない可能性があります。最新のブラウザをご利用ください。</div>

  <input type="hidden" value="./" id="js-base-url">

  <div class="l-wrap js-wrap">
    <div class="l-header l-header-admin js-header">
      <div class="l-header-top u-clear">
        <div class="l-header-logo">
          <%= link_to root_path, class: "logo" do %>
            <%= image_tag("logo-admin.png", height: "28", width: "138") %>
          <% end %>
        </div>
        <div class="l-header-text">
          <p>ADMIN PAGE</p>
        </div>
      </div>
    </div>

    <div class="l-container u-clear content">
      <div class="l-main-block"></div>
      <div style="color: red;" id="flash"><%= flash[:notice] if flash[:notice]  %></div>
      <%= form_for @admin_user, url: admin_index_path do |f| %>
        <label for="user-id" class="form-title">USER ID</label>
        <%= f.text_field :username, class: "input input-text", id: "user-id" %>
        <label for="password" class="form-title">PASSWORD</label>
        <%= f.password_field :password, class: "input input-text", id: "password" %>
        <%= f.submit "Login", class: "form-button button button-text" %>
      <% end %>
    </div>

    <div class="l-footer l-footer-admin">
      <div class="l-footer-copyright">
        <small class="copyright">&copy;copyright</small>
      </div>
    </div>
  </div>
</body>

<% content_for :extra_javascripts do %>
  <%= javascript_include_tag "admin" %>
<% end %>

app/views/admins/index.html.erb
<div class="l-wrap js-wrap">
  <div class="l-header l-header-admin js-header">
    <div class="l-header-top u-clear">
      <div class="l-header-logo">
        <a class="logo " href="./">
          <%= image_tag("logo-admin.png", height: "28", width: "138") %>
        </a>
      </div>
      <div class="l-header-text">
        <p>ADMIN PAGE</p>
      </div>
    </div>
  </div>

  <div class="l-container u-clear content">
    <div class="l-main-block"></div>
    <div style="color: red;"><%= flash[:notice] if flash[:notice]  %></div>
    <%= form_for @admin_user, url: admins_path do |f| %>
      <label for="user-id" class="form-title">USER ID</label>
      <%= f.text_field :username, class: "input input-text", id: "user-id" %>
      <label for="password" class="form-title">PASSWORD</label>
      <%= f.password_field :password, class: "input input-text", id: "password" %>
      <%= f.submit "Login", class: "form-button button button-text" %>
    <% end %>
  </div>

  <div class="l-footer l-footer-admin">
    <div class="l-footer-copyright">
      <small class="copyright">&copy;copyright</small>
    </div>
  </div>
</div>

app/views/blogs/_form.html.erb
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <meta name="description" content="sample text,sample tex">
  <meta name="keywords" content="word1,word2,word3">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta property="og:title" content="">
  <meta property="og:description" content="sample text,sample tex">
  <meta property="og:url" content="">
  <meta property="og:site_name" content="">
  <meta property="og:type" content="blog">
  <meta property="fb:admins" content="">
  <meta property="og:image" content="assets/images/common/ogp.png">
  <meta name="apple-mobile-web-app-title" content="">
  <link rel="shortcut icon" href="assets/images/common/favicon.ico">
  <link rel="apple-touch-icon-precomposed" href="images/common/apple-touch-icon-precomposed.png">
</head>

<body id="js-body">
  <div id="fb-root"></div>

  <noscript class="for-no-js">Javascriptを有効にしてください。</noscript>
  <div class="for-old">お使いのOS・ブラウザでは、本サイトを適切に閲覧できない可能性があります。最新のブラウザをご利用ください。</div>

  <input type="hidden" value="./" id="js-base-url">

  <div class="l-wrap js-wrap">
    <div class="l-header l-header-admin js-header">
      <div class="l-header-top u-clear">
        <div class="l-header-logo">
          <%= link_to root_path, class: "logo" do %>
            <%= image_tag("logo-admin.png", height: "28", width: "138") %>
          <% end %>
        </div>
        <div class="l-header-text">
          <p>ADMIN PAGE</p>
        </div>
      </div>
    </div>

    <div class="l-container u-clear">
      <div class="l-main js-main">
      <div class="l-main-block"></div>
      <% if @blog.errors.present? %>
        <% @blog.errors.full_messages.each do |message| %>
          <div style="color: red;" id="flash"><%= message  %></div>
        <% end %>
      <% end %>
      <label for="image" class="form-title">EYE CATCH IMAGE
        <div class="form-file u-clear" style="padding-left: 10px">
          <% if @blog.eye_catch.present? %>
            <%= @blog.eye_catch_file_name %>
          <% end %>
          <span class="form-file-button">UPLOAD</span>
        </div>
      </label>
      <%= f.file_field :eye_catch, class: "input input-image", id: "image" %>
      <label for="title" class="form-title">TITLE</label>
      <div class="form-body">
        <%= f.input_field :title, class: "input input-text", id: "title" %>
      </div>
      <label for="contents" class="form-title">CONTENTS</label>
      <div class="form-textarea">
        <%= f.input_field :contents, class: "input input-contents", id: "inquiry" %>
      </div>
      <%= f.submit "Submit", class: "form-button button button-text" %>
      <%= link_to "Back", blogs_admin_index_path, class: "button button-text form-button" %>
    </div>
    <div class="l-footer l-footer-admin">
      <div class="l-footer-copyright">
        <small class="copyright">&copy;copyright</small>
      </div>
    </div>
  </div>
</body>

<% content_for :extra_javascripts do %>
  <%= javascript_include_tag "admin" %>
<% end %>

app/views/blogs/_toggle_list.html.erb
<div class="l-header-hamburger">
  <button href="#" class="hamburger js-hamburger" >
    <span class="hamburger-item"></span>
    <span class="hamburger-item"></span>
    <span class="hamburger-item"></span>
  </button>
</div>

<div class="nav js-nav">
  <ul class="nav-list">
    <li class="nav-item">
    <%= link_to "TOP", blogs_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
    <a href="#" class="nav-link">Facebook</a>
    </li>
    <li class="nav-item">
    <a href="#" class="nav-link">Twitter</a>
    </li>
  </ul>
</div>

app/views/blogs/admin_blogs.html.erb
<div class="l-wrap js-wrap">
  <div class="l-header l-header-admin js-header">
    <div class="l-header-top u-clear">
      <div class="l-header-logo">
        <a class="logo " href="./">
          <%= image_tag("logo-admin.png", height: "28", width: "138") %>
        </a>
      </div>
      <div class="l-header-text">
        <%= link_to "LOGOUT", logout_admins_path %>
      </div>
    </div>
  </div>

  <div class="l-container u-clear">
    <div class="l-main js-main">
    <div class="l-main-block"></div>
    <%= link_to "New Article", new_blog_path, class: "button button-text l-main-button" %>
    <ul class="archive archive-admin">
      <% @blogs.each do |blog| %>
        <li class="archive-item">
          <a href="#" class="post-article">
            <div class="post-article-date" datetime="2016-9-16"><%= blog.created_at.strftime("%F") %></div>
            <h1 class="post-article-title"><%= blog.title %></h1>
          </a>
        </li>
      <% end %>
    </ul>
    </div>
  </div>

  <div class="l-footer l-footer-admin">
    <div class="l-footer-copyright">
      <small class="copyright">&copy;copyright</small>
    </div>
  </div>
</div>

app/views/blogs/archive.html.erb
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <meta name="description" content="sample text,sample tex">
  <meta name="keywords" content="word1,word2,word3">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta property="og:title" content="">
  <meta property="og:description" content="sample text,sample tex">
  <meta property="og:url" content="">
  <meta property="og:site_name" content="">
  <meta property="og:type" content="blog">
  <meta property="fb:admins" content="">
  <meta property="og:image" content="assets/images/common/ogp.png">
  <meta name="apple-mobile-web-app-title" content="">
  <link rel="shortcut icon" href="assets/images/common/favicon.ico">
  <link rel="apple-touch-icon-precomposed" href="images/common/apple-touch-icon-precomposed.png">
</head>

<body id="js-body">
  <div id="fb-root"></div>

  <noscript class="for-no-js">Javascriptを有効にしてください。</noscript>
  <div class="for-old">お使いのOS・ブラウザでは、本サイトを適切に閲覧できない可能性があります。最新のブラウザをご利用ください。</div>

  <input type="hidden" value="./" id="js-base-url">

  <div class="l-wrap js-wrap">
    <div class="l-header  js-header">
      <div class="l-header-top u-clear">
        <div class="l-header-logo">
          <div class="logo ">
            <%= image_tag("logo.png", height: "28", width: "138") %>
          </div>
        </div>
        <%= render "toggle_list" %>
      </div>
    </div>

    <div class="l-container u-clear">
      <div class="l-main js-main">
        <div class="l-main-block"></div>
        <div class="page-number">
          Page <span ><%= "#{params[:page] || 1} / #{@total_page}" %></span>
        </div>
        <div class="archive">
          <ul class="archive-list">
            <% @blogs.each do |blog| %>
              <li class="archive-item">
                <div class="card">
                  <%= link_to single_view_blogs_path(blog_id: blog.id), class: "card-link" do %>
                    <%= image_tag blog.eye_catch.url(:original), class: "card-image" %>
                    <div class="card-bottom">
                      <h1 class="card-title"><%= blog.title %></h1>
                      <div class="card-date" datetime="2016-9-16">
                        <%= blog.created_at.strftime("%F") %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="blog-main-pagination">
          <%= paginate @blogs %>
        </div>
      </div>
    </div>
  </div>

  <div class="l-footer ">
    <div class="l-footer-button">
      <a class="page-top js-scroll" href="#js-body" id ="backToTopBtn">
        <span class="page-top-arrow"></span>
      </a>
    </div>
    <div class="l-footer-copyright">
      <small class="copyright">&copy;copyright</small>
    </div>
  </div>
</body>

<% content_for :extra_javascripts do %>
  <%= javascript_include_tag "blogs" %>
<% end %>

app/views/blogs/edit.html.erb
<%= simple_form_for(@blog, url: blog_path, :method => :put) do |f| %>
  <%= render "form", f: f %>
<% end %>

app/views/blogs/index.html.erb
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <meta name="description" content="sample text,sample tex">
  <meta name="keywords" content="word1,word2,word3">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta property="og:title" content="">
  <meta property="og:description" content="sample text,sample tex">
  <meta property="og:url" content="">
  <meta property="og:site_name" content="">
  <meta property="og:type" content="blog">
  <meta property="fb:admins" content="">
  <meta property="og:image" content="assets/images/common/ogp.png">
  <meta name="apple-mobile-web-app-title" content="">
  <link rel="shortcut icon" href="assets/images/common/favicon.ico">
  <link rel="apple-touch-icon-precomposed" href="images/common/apple-touch-icon-precomposed.png">
</head>

<body id="js-body">
  <div id="fb-root"></div>

  <noscript class="for-no-js">Javascriptを有効にしてください。</noscript>
  <div class="for-old">お使いのOS・ブラウザでは、本サイトを適切に閲覧できない可能性があります。最新のブラウザをご利用ください。</div>

  <input type="hidden" value="./" id="js-base-url">

  <div class="l-wrap js-wrap">
    <div class="l-header  js-header">
      <div class="l-header-top u-clear">
        <div class="l-header-logo">
          <div class="logo ">
            <%= image_tag("logo.png", height: "28", width: "138") %>
          </div>
        </div>
        <%= render "toggle_list" %>
      </div>
    </div>

    <div class="l-container u-clear">
      <div class="l-main js-main">
        <div class="l-main-block"></div>
        <div class="archive">
          <ul class="archive-list">
            <% @blogs.each do |blog| %>
              <li class="archive-item">
                <div class="card">
                  <%= link_to single_view_blogs_path(blog_id: blog.id), class: "card-link" do %>
                    <%= image_tag blog.eye_catch.url(:original), class: "card-image" %>
                    <div class="card-bottom">
                      <h1 class="card-title"><%= blog.title %></h1>
                      <div class="card-date" datetime="2016-9-16">
                        <%= blog.created_at.strftime("%F") %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
        <% if @blogs.present? %>
          <%= link_to "More", archive_blogs_path, class: "archive-button button button-text" %>
        <% end%>
      </div>
    </div>

    <div class="l-footer ">
      <div class="l-footer-button">
        <a class="page-top js-scroll" href="#top" id ="backToTopBtn">
          <span class="page-top-arrow"></span>
        </a>
      </div>
      <div class="l-footer-copyright">
        <small class="copyright">&copy;copyright</small>
      </div>
    </div>
  </div>
</body>

<% content_for :extra_javascripts do %>
  <%= javascript_include_tag "blogs" %>
<% end %>

app/views/blogs/new.html.erb
<%= simple_form_for(@blog, url: blogs_path, :method => :post) do |f| %>
  <%= render "form", f: f %>
<% end %>

app/views/blogs/single_view.html.erb
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <meta name="description" content="sample text,sample tex">
  <meta name="keywords" content="word1,word2,word3">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta property="og:title" content="">
  <meta property="og:description" content="sample text,sample tex">
  <meta property="og:url" content="">
  <meta property="og:site_name" content="">
  <meta property="og:type" content="blog">
  <meta property="fb:admins" content="">
  <meta property="og:image" content="assets/images/common/ogp.png">
  <meta name="apple-mobile-web-app-title" content="">
  <link rel="shortcut icon" href="assets/images/common/favicon.ico">
  <link rel="apple-touch-icon-precomposed" href="images/common/apple-touch-icon-precomposed.png">
</head>

<body id="js-body">
  <div id="fb-root"></div>

  <noscript class="for-no-js">Javascriptを有効にしてください。</noscript>
  <div class="for-old">お使いのOS・ブラウザでは、本サイトを適切に閲覧できない可能性があります。最新のブラウザをご利用ください。</div>

  <input type="hidden" value="./" id="js-base-url">

  <div class="l-wrap js-wrap">
    <div class="l-header  js-header">
      <div class="l-header-top u-clear">
        <div class="l-header-logo">
          <div class="logo ">
            <%= image_tag("logo.png", height: "28", width: "138") %>
          </div>
        </div>
        <%= render "toggle_list" %>
      </div>
    </div>

    <div class="l-main js-main">
      <div class="l-main-block"></div>
      <div class="single">
        <%= image_tag @blog.eye_catch.url(:original), class: "single-image" %>
        <div class="l-container u-clear">
          <h1 class="single-title"><%= @blog.title %></h1>
          <div class="single-date" datetime="2016-9-16">
            <%= @blog.created_at.strftime("%F") %>
          </div>
          <p class="single-desc">
            <%= @blog.contents %>
          </p>
          <%= link_to "Top", blogs_path, class: "single-button button button-text" %>
        </div>
      </div>
    </div>
  </div>
  <div class="l-footer ">
    <div class="l-footer-button">
      <a class="page-top js-scroll" href="#js-body" id ="backToTopBtn">
        <span class="page-top-arrow"></span>
      </a>
    </div>
    <div class="l-footer-copyright">
      <small class="copyright">&copy;copyright</small>
    </div>
  </div>
</body>

<% content_for :extra_javascripts do %>
  <%= javascript_include_tag "blogs" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>

</html>